apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      tolerations:
        - key: 'node.kubernetes.io/not-ready'
          operator: 'Exists'
          effect: 'NoSchedule'
        - key: 'node.gke.io/balloon-pod-resize'
          operator: 'Exists'
          effect: 'NoSchedule'
      containers:
        - name: user-service
          # image: yaseralazm/user-service
          image: gcr.io/tms-dev-464113/user-service
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres-srv:5432/tms?schema=public
            - name: JWT_SECRET
              value: your-super-secret-key-change-this-in-production
            - name: NODE_ENV
              value: development # Change this manually for prod
            - name: PORT
              value: '4001'
            - name: KAFKA_BROKERS
              value: kafka-srv:9092
            - name: KAFKA_CLIENT_ID
              value: user-service
            - name: JWT_KID
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: jwt-kid
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: jwt-issuer
            - name: JWT_PRIVATE_KEY_PEM
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: jwt-private-key
            - name: JWT_PUBLIC_KEY_PEM
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: jwt-public-key
          ports:
            - containerPort: 4001
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-srv -p 5432 -U postgres; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
        - name: migrate
          # image: yaseralazm/user-service
          image: gcr.io/tms-dev-464113/user-service
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres-srv:5432/tms?schema=public
          command:
            - npx
            - prisma
            - migrate
            - deploy
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP
